### ISSUE TITLE
Library goes into an infinite loop

### ISSUE THREAD

**Issue by avinkum2** [ciscospark/spark-js-sdk#748] opened 2017-11-15 17:58 UTC
The KMS library seems to go into an infinite loop if I retrieve authorizations for a resource that has more than 110 or so bound users. Here is the stacktrace that I saw:

kms: retrieved authorization list
kms: request timed out; request id: cf570fcf-2071-486b-b24f-2ffeb78fa971; timeout: 6000
kms: request error KmsError: undefined
KMS_REQUEST_ID: cf570fcf-2071-486b-b24f-2ffeb78fa971
at KmsError.ExtendableBuiltin (/Users/avinkum2/CS/onboarding/app/node_modules/@ciscospark/common/dist/exception.js:50:44)
at KmsError.Exception (/Users/avinkum2/CS/onboarding/app/node_modules/@ciscospark/common/dist/exception.js:97:142)
at new KmsError (/Users/avinkum2/CS/onboarding/app/node_modules/@ciscospark/internal-plugin-encryption/dist/kms-errors.js:54:123)
at /Users/avinkum2/CS/onboarding/app/node_modules/@ciscospark/internal-plugin-encryption/dist/kms-batcher.js:161:20
at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by ianwremmel** [comment] 2017-11-15 18:41
Is this the same issue as #747?

**Comment by avinkum2** [comment] 2017-11-15 21:56
Nope, #747 is about the case when the caller is not authorized to the resource. In that case we see a crash with an out of memory error.

In this case the caller is authorized to the resource, but the resource has like 110 authorizations on it. So what I see is that the library tries to fetch the authorizations, eventually times out and runs in to “KmsError: undefined” problem. After that the library goes into an infinite loop. But unlike #747 there is no out of memory crash this time.

I can show the problem if needed.. its reproducible every time.

**Comment by ianwremmel** [comment] 2017-12-01 17:00
Sorry, I think I may have mean #749. It looks like the original reason for opening #749 has been resolved. Is this still an issue?

**Comment by avinkum2** [comment] 2017-12-04 14:37
I can test again and let you know. Is there a specific version you would like to validate on? These are the versions that we use right now:

"@ciscospark/internal-plugin-encryption": "1.16.0",
"@ciscospark/spark-core": "1.14.3",

**Comment by ianwremmel** [comment] 2017-12-04 17:31
Latest, please.

At present, that appears to be 

```
"@ciscospark/internal-plugin-encryption": "1.19.9", 
"@ciscospark/spark-core": "1.19.9",
```

**Comment by avinkum2** [comment] 2017-12-04 18:46
I still see the same problem. Here is what I have in the logs:

spark-store: constructing boundedStorage
spark-store: retrieving Device:@
storage: getting binding for `Device`
memory-store-adapter: returning binding
spark-store: retrieving Credentials:@
storage: getting binding for `Credentials`
memory-store-adapter: returning binding
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): initing `@`
spark-store: retrieving Device:@
storage: made binding for `Device`
storage: made binding for `Credentials`
memory-store-adapter: reading `@`
memory-store-adapter: reading `@`
memory-store-adapter: reading `@`
storage(Device): no data for `@`, continuing
plugin-storage(Device): no data for `@`, continuing
storage(Credentials): no data for `@`, continuing
device: registering
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): initing `@`
spark-store: retrieving Credentials:@
storage: getting binding for `Credentials`
storage: found binding for `Credentials`
memory-store-adapter: reading `@`
plugin-storage(Credentials): no data for `@`, continuing
spark-store: setting Credentials:@
storage: getting binding for `Credentials`
storage: found binding for `Credentials`
memory-store-adapter: writing `@`
device: received registration payload
mercury: connecting
mercury: executing connection attempt 0
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): already inited `@`
socket: creating WebSocket
socket: waiting for server
spark-store: setting Device:@
storage: getting binding for `Device`
storage: found binding for `Device`
memory-store-adapter: writing `@`
socket: connected
socket: authorizing
socket: sequence number:  1
socket: ping dd758302-28ac-41fa-a014-add6b10adc31
socket: authorized
mercury: connected
kms: creating context
kms: retrieving KMS static public key
kms: fetching KMS details
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): already inited `@`
socket: sequence number:  2
socket: pong dd758302-28ac-41fa-a014-add6b10adc31
kms: fetched KMS details
kms: creating local ephemeral key
kms: retrieving KMS cluster
kms: submitting ephemeral key request
mercury: already connected, will not connect again
kms: wrapping ephemeral key request
kms: retrieving KMS cluster
kms: batched-request-length 1
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): already inited `@`
socket: sequence number:  3
kms: received kms message
kms: retrieving KMS static public key
kms: received ecdhe message
kms-batcher: received kms message
kms: deriving final ephemeral key
kms: derived final ephemeral key
kms: wrapping kms request
kms: retrieving KMS cluster
kms: batched-request-length 1
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): already inited `@`
kms: request timed out; request id: b6480082-2a96-4559-ac13-9e3808d7cf68; timeout: 6000
(node:5832) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): KmsError: [object Object]
KMS_REQUEST_ID: b6480082-2a96-4559-ac13-9e3808d7cf68
mercury: already connected, will not connect again
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): already inited `@`
kms: wrapping kms request
kms: retrieving KMS cluster
kms: batched-request-length 1
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): already inited `@`
socket: ping dcba93a3-f8ab-4b7b-9551-9c429eb45c35
socket: sequence number:  4
socket: pong dcba93a3-f8ab-4b7b-9551-9c429eb45c35
kms: request timed out; request id: d3ea0a53-624c-4e80-b2f2-2f76c1c48e3c; timeout: 12000
mercury: already connected, will not connect again
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): already inited `@`
kms: wrapping kms request
(node:5832) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): KmsError: [object Object]
KMS_REQUEST_ID: d3ea0a53-624c-4e80-b2f2-2f76c1c48e3c
kms: retrieving KMS cluster
kms: batched-request-length 1
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): already inited `@`
socket: ping 82c60a93-6a65-435a-ac1f-0d767382a2d4
socket: sequence number:  5
socket: pong 82c60a93-6a65-435a-ac1f-0d767382a2d4
kms: request timed out; request id: 2f876809-8793-4418-9c80-78a887ff4693; timeout: 24000
kms: exceeded maximum KMS request retries; negotiating new ecdh key
mercury: already connected, will not connect again
kms: creating context
kms: retrieving KMS static public key
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): already inited `@`
kms: creating local ephemeral key
kms: retrieving KMS cluster
kms: submitting ephemeral key request
mercury: already connected, will not connect again
kms: wrapping ephemeral key request
(node:5832) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): KmsError: [object Object]
KMS_REQUEST_ID: 2f876809-8793-4418-9c80-78a887ff4693
kms: retrieving KMS cluster
kms: batched-request-length 1
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): already inited `@`
socket: sequence number:  6
kms: received kms message
kms: retrieving KMS static public key
kms: received ecdhe message
kms-batcher: received kms message
kms: deriving final ephemeral key
kms: derived final ephemeral key
kms: wrapping kms request
kms: retrieving KMS cluster
kms: batched-request-length 1
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): already inited `@`
socket: ping 71527dbb-9e23-4efa-b761-f61900ab6a3a
socket: sequence number:  7
socket: pong 71527dbb-9e23-4efa-b761-f61900ab6a3a
ccc-status.refreshStatus called
REDIS NOT AVAILABLE: Running locally
kms: request timed out; request id: 22646ec2-c1a3-436b-90ef-f3fc94cda209; timeout: 6000
mercury: already connected, will not connect again
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): already inited `@`
kms: wrapping kms request
(node:5832) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18): KmsError: [object Object]
KMS_REQUEST_ID: 22646ec2-c1a3-436b-90ef-f3fc94cda209
kms: retrieving KMS cluster
kms: batched-request-length 1
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Device): waiting to init key `@`
plugin-storage(Device): already inited `@`
plugin-storage(Credentials): waiting to init key `@`
plugin-storage(Credentials): already inited `@`

**Comment by ianwremmel** [comment] 2017-12-04 22:29
What does the unencrypted request payload look like? How do you know how many authorizations the resource has? Have you confirmed with the server folks that KMS is responding in a timely fashion?

There are *a lot* of cases where, rather than supplying an error back to the client, the client simply receives no response. The only steps the client (i.e. the sdk) can take are to retry the request. Once we've retried with a timeout up to 32000ms, the only thing we can assume is that our ecdh token is somehow invalid and therefore renegotiate ecdh and start the process over.

**Comment by avinkum2** [comment] 2017-12-05 14:57
The only difference between the working and non-working cases is the number of authorizations on the resource. List authorizations stops working if the number of authorizations on the resource is more than 110 or so.

I can IM you details of my test account and the resource if you want to take a closer look into the problem. I see this failure every time.

**Comment by ianwremmel** [comment] 2017-12-08 23:48
As far as I can tell, this is a limitation of the service and not something we can address in the sdk. I'm going to close this as wontfix and defer to the server team to propose a new API to address the problem.

**Closed by ianwremmel** 2017-12-08 23:48 UTC

**Comment by avinkum2** [comment] 2017-12-11 14:59
I understand the limitation on the service side. But shouldn’t the SDK client handle it gracefully instead of going into an infinite loop?

**Comment by ianwremmel** [comment] 2017-12-11 17:26
ideally, yes, but there's really nothing we can do. This is one of many error conditions where we don't get any response of any kind from the service. Without a response, the only the we can do is assume the ECDH key is somehow invalid, negotiate a new one, and try again.
