### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by RichLogan** [ciscospark/spark-js-sdk#12] opened 2016-08-02 15:20 UTC
`$ npm install ciscospark` seems to be failing for myself and a colleague, giving: 

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "install" "--save" "ciscospark"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5

npm ERR! No compatible version found: @ciscospark/spark-core@^0.7.0-alpha.f22f099e
npm ERR! Valid install targets:
npm ERR! 0.7.0-alpha.ce9393d4, 0.7.0-alpha.a5bc0482, 0.7.0-alpha.3266717c, 0.6.9, 0.6.6, 0.6.4, 0.6.3, 0.6.1, 0.6.0, 0.6.0-35, 0.6.0-34
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rilogan/Projects/SparkVideo/npm-debug.log
```

`$ npm view @ciscospark/plugin-phone versions` doesn't seem to show the asked for *0.7.0-alpha.f22f099e* version. 

For the record, `$ npm install ciscospark@0.6.9` works fine.

**Comment by ianwremmel** [comment] 2016-08-02 16:34
Hi Rich. For now, stick the explicit 0.6.9 install. 0.7.0 isn't ready yet and wasn't supposed to be installed automatically. It looks like a tooling bug that's unexpectedly marking it as "latest" on npm. I'll look into that shortly.

**Comment by ianwremmel** [comment] 2016-08-02 16:35
Caused by https://github.com/lerna/lerna/issues/295

**Comment by ianwremmel** [comment] 2016-08-02 17:58
Actually, not a lerna bug. Appears to be a result of the hack to deal with https://github.com/lerna/lerna/issues/64 (which is really an npm bug, but npm seems to have removed the issue tracker for their website).

**Comment by RichLogan** [comment] 2016-08-03 09:07
Hi @ianwremmel, when I try and follow the build instructions (in order to build for the browser functionality) `$ npm install` gives `npm ERR! 404  'spark-js-sdk--test-users' is not in the npm registry`. Removing that dependency allows install to complete, but then `npm run bootstrap` fails also. 

It looks like swapping out `$ npm run bootstrap` for just `$ lerna bootstrap` allows the rest of the build to run properly and generate the bundle. This was working off of the c49ca68 commit. 

Please let me know if it's just me doing something wrong! I don't have much experience with Node/npm.

**Comment by ianwremmel** [comment] 2016-08-03 16:40
no, you're doing everything correctly. that's a module we're not yet ready to release publicly, but I thought I had rigged it up so it wouldn't be an issue.

Removing the dependency should fix it for you in the short term. What was the failure with `npm run bootstrap` once you removed it?

**Comment by ianwremmel** [comment] 2016-08-03 17:03
@RichLogan, I'll have a much simpler method for you in a few days. Just need to get some other processes unblocked first.

**Comment by RichLogan** [comment] 2016-08-03 18:36
@ianwremmel the `$ npm run bootstrap` returned something like `lerna bootstrap failed` immediately, so I tried to run just `$ lerna bootstrap` to see if it a gave a more verbose error but it seemed to it's thing fine.  

Thanks for all your quick responses. My initial testing with the browerified bundle.js seems to show it working after getting past these small hiccups.

**Comment by ianwremmel** [comment] 2016-08-03 18:39
Great! glad it's working now. 

I'll have to verify it works over the next few days, but my plan is to add a new module called `@ciscospark/bundle` that, when installed, produces a bundle.js in the directory from which you ran the `npm install` command.

**Closed** 2016-08-05 03:20 UTC
Labels: bug, ciscospark
