### ISSUE TITLE
Call status changes to 'initiated' on hangup

### ISSUE THREAD

**Issue by Popl7** [ciscospark/spark-js-sdk#403] opened 2017-01-05 10:25 UTC
When I end a call the status changed callback is called with status 'initiated'.
Right after this the call status changes to 'disconnected'.
This causes unwanted callback actions being run on hangup.

This is how it looks in my Chrome Browser Console:
```
let call = ciscospark.phone.dial('xxxx@yyy.nl')
call.on(`change:status`, () => console.log('status changed: ', call.status));
call.hangup()
status changed:  initiated
status changed:  disconnected
```

**Comment by ianwremmel** [comment] 2017-01-09 20:40
yep, this is one of the issues preventing the calling features to enter GA. timeline is still a bit fuzzy, but calling features should be prioritized soon

**Comment by ianwremmel** [comment] 2017-05-17 21:56
I believe this has been fixed. Please open a new ticket if you still see issues.

**Comment by ianwremmel** [comment] 2017-05-17 22:03
Actually, I take that back, I misread your scenario.

**Comment by ianwremmel** [comment] 2017-05-17 22:06
What state are you expecting? In my opinion, as soon as a `Call` is produced, that call is initiated. The request is in flight, and the remote party is going be notified. In the scenario you're describing, are you calling hangup because of a user action or because somewhere on the same tick that dial was called, some piece of logic decided it was time to hangup?

I'm not sure this is behavior that should change, but I'd like to understand your use case a bit better.

**Comment by Popl7** [comment] 2017-05-18 07:09
It occurs when I am in a call, status connected and I call hangup().
The status callback function receives a initiated before it eventually goes to disconnected.

**Comment by ianwremmel** [comment] 2017-05-18 17:56
Oh, I see, so, it's transitioning through `initiated` when you end a call, not when you cancel a call before it's fully setup. I'll take a look through the tests and see if I can figure out why they're not catching that behavior; that's definitely a bug.

**Comment by ianwremmel** [comment] 2017-05-19 02:20
Got it figured out. There were some unexpected timing conditions caused by how ampersand-state does computed properties. There's a PR out there that refactors the tests to make sure it doesn't happen again and addresses the underlying issue. I'm coordinating a number of different PRs right, but it should get merged sometime in the next few days.

**Closed** 2017-05-21 01:50 UTC
